DEV-661 Fixed styling issues and made plus and minus button match lig…
vertotrade/verto.ui pull request #135
Opened 2023-08-17 16:01 UTC by willau24

Fixed styling issues and made plus and minus button match light/dark mode

2023-08-17 18:24 UTC, yuushazen requested changes
Please fix lint errors

2023-08-17 18:24 UTC, yuushazen commented on .vscode/launch.json
> +            "name": "Launch Chrome against localhost",
Should this be commited? The app doesn’t run on this port either

2023-08-17 18:24 UTC, yuushazen commented on apps/web/src/components/PositionCard/index.tsx
> +                mb="0px">
Can you just remove the mb property?

2023-08-18 15:21 UTC, yuushazen commented
Please squash the commits before merging

2023-08-18 17:14 UTC, willau24 commented
> 

Ok I think I just squashed the other commits, should be good to go

2023-08-21 15:15 UTC, yuushazen approved these changes

2023-08-22 12:54 UTC, vertotrade approved these changes
LGTM

2023-08-22 13:18 UTC, merged