fixed account check for ui kit user menu
vertotrade/verto.ui pull request #183
Opened 2023-11-28 13:48 UTC by naveed-dev04

Fixed account check for ui kit user menu

2023-11-28 17:50 UTC, yuushazen approved these changes

2023-11-28 18:00 UTC, yuushazen requested changes
Please do PRs against the NFT marketplace epic branch

2023-11-29 07:02 UTC, naveed-dev04 commented
> Please do PRs against the NFT marketplace epic branch

This issue is already fixed in NFT marketplace epic branch but not fixed in main branch that's why i created PR against main branch.

2023-12-22 13:48 UTC, closed without merging

2023-12-22 13:48 UTC, vertotrade commented
already fixed on epic branch